// AUTO-GENERATED by atmn pull
// DO NOT EDIT MANUALLY

declare module "@useautumn/sdk" {
  // Base types
  export type Feature = import("./autumn.config").Feature;
  export type Plan = import("./autumn.config").Plan;
}
