// AUTO-GENERATED by atmn pull
// DO NOT EDIT MANUALLY

declare module "@useautumn/sdk" {
  // Features
  export const tokens_in: Feature;
  export const chat_messages: Feature;
  export const ai_budget: Feature;
  export const sandbox_hours: Feature;
  export const tokens_out: Feature;
  export const usage_usd: Feature;

  // Plans
  export const free_plan: Plan;
  export const btca_pro: Plan;

  // Base types
  export type Feature = import("atmn").Feature;
  export type Plan = import("atmn").Plan;
}
